server:
  port: 5002
  servlet:
    context-path: /api/v1

cors:
  allowed-origins: http://localhost:5173,http://localhost:3001

spring:
  application:
    name: mdb-admin-bff-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8484/realms/mdb-realm}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8484/realms/mdb-realm/protocol/openid-connect/certs}
  
  kafka:
    #    kafka:
#    bootstrap-servers: localhost:9093
#      producer:
#        key-serializer: org.apache.kafka.common.serialization.StringSerializer
#        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: localhost:9093
    consumer:
      group-id: mdb-admin-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

grpc:
  client:
    media-gateway:
      host: ${MEDIA_GATEWAY_HOST:localhost}
      port: ${MEDIA_GATEWAY_PORT:9090}
    user-gateway:
      host: ${USER_GATEWAY_HOST:localhost}
      #port: ${USER_GATEWAY_PORT:6001}
      port: ${USER_GATEWAY_PORT:6005}

  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always

info:
  app:
    name: mdb-admin-bff-service
    version: 1.0.0

resilience4j:
  circuitbreaker:
    instances:
      externalService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  ratelimiter:
    instances:
      externalService:
        limitForPeriod: 10
        limitRefreshPeriod: 10s
        timeoutDuration: 0
      notifications:
        limitForPeriod: 10
        limitRefreshPeriod: 10s
        timeoutDuration: 0
      login:
        limitForPeriod: 5
        limitRefreshPeriod: 900s # 15 minutes
        timeoutDuration: 0

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: 86400000 # 1 day
  refresh-expiration: 604800000 # 7 days

keycloak:
  token-uri: ${KEYCLOAK_TOKEN_URI:http://localhost:8484/realms/mdb-realm/protocol/openid-connect/token}
  client-id: ${KEYCLOAK_CLIENT_ID:mdb-admin-client}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:BMDvswa0MHpQNnD7yPYL1K0FwIC1kNdF}


logging:
  level:
    root: INFO
    com.mdb.adminbff: DEBUG
    org.apache.kafka: OFF
    org.springframework.kafka: OFF
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId}] %-5level %logger{36} - %msg%n"
